NIST BGP-SRx V4.2.1

diff --git a/srx-crypto-api/tools/qsrx-make-cert b/srx-crypto-api/tools/qsrx-make-cert
--- a/srx-crypto-api/tools/qsrx-make-cert
+++ b/srx-crypto-api/tools/qsrx-make-cert
@@ -10,8 +10,6 @@
 # uses the key file though.
 #
 
-echo "$PATH" 
-
 EXT_PEM="pem"
 EXT_CERT="cert"
 EXT_CSR="csr"
@@ -23,10 +21,6 @@ if [ "$1" == "--cnf" ] ; then
   shift
 fi
 
-if [ "$1" == "" ] ; then
-  echo "call $0 [--cnf <location of qsrx-router-key.cnf> ] <keyname>"
-  exit 1
-fi
 
 if [ "$QSRX_CONF_HOME" == "" ] ; then
   QSRX_CONF_HOME="/etc"
@@ -36,6 +30,14 @@ QSRX_CONF_FILE=$QSRX_CONF_HOME/qsrx-router-key.cnf
 QSRX_VIEW=qsrx-view-subject
 QSRX_MAKE_KEY=qsrx-make-key
 QSRX_SERIAL=20140220001
+
+if [ "$1" == "" ] || [ ! -e $QSRX_CONF_FILE ] ; then
+  if [ ! -e $QSRX_CONF_FILE ] ; then
+    echo "File $QSRX_CONF_FILE not found!"
+  fi
+  echo "call $0 [--cnf <location of qsrx-router-key.cnf> ] <keyname>"
+  exit 1
+fi
 
 which $QSRX_VIEW > /dev/null 2>&1
 if [ $? -eq 1 ] ; then
@@ -56,6 +58,9 @@ if [ -e "$1.$EXT_PEM" ] ; then
   # Create Certificate
   echo "Create Certificate for $1"
   openssl x509 -sha256 -extfile $QSRX_CONF_FILE -extensions bgpsec_router_ext -set_serial $QSRX_SERIAL -in $1.$EXT_CSR -outform DER -out $1.$EXT_CERT -req -signkey $1.$EXT_PEM -days 365
+
+  echo "Create BIRD compatible public key $1.$SUBJECT.0.key"
+  openssl x509 -inform DER -noout -pubkey -in $1.$EXT_CERT | openssl pkey -pubin -outform DER -out $1.$SUBJECT.0.key
 
   # Remove certificate request
   rm -f $1.$EXT_CSR
